# Generated by Django 4.2.5 on 2023-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_slide_image_slide_image_design_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
